### ISSUE TITLE
Download the dataset

### ISSUE THREAD

**Issue by huyhoang17** [Phymond/HME100K#1]
Hi, @Phymond 

Can you help me upload the data on the other site, like GoogleDrive or DropBox? Because I can not create an account on this [ai.100tal.com](https://ai.100tal.com/dataset) website, therefore I can not download the dataset.
Thank you so much. Hope to see your response!

**Comment by Phymond** [comment]
> Hi, @Phymond
> 
> Can you help me upload the data on the other site, like GoogleDrive or DropBox? Because I can not create an account on this [ai.100tal.com](https://ai.100tal.com/dataset) website, therefore I can not download the dataset. Thank you so much. Hope to see your response!

hi @huyhoang17 , the company doesn't allow to upload the data to other websites. What's the problem when you create an account??

**Comment by huyhoang17** [comment]
@Phymond 

I'm not Chinese, therefore I can not create an account on this website :/

**Comment by Phymond** [comment]
> 

Could you give an email? I will send you the dataset

**Comment by huyhoang17** [comment]
@Phymond 
My email: hoangphan0710@gmail.com
Thank you so much!!

**Comment by revidee** [comment]
@Phymond I would like to chime in on the offer, since I can't register at ai.100tal.com aswell. They seem to require some kind of asia-based mobile phone number i suppose, which I do not and cannot own here in Germany.

My email: <edited out since i have received the dataset>
I would also greatly appreciate having access to the dataset :).

I think it would be greatly beneficial for the Datasets adoption among researchers if the dataset would be made available world-wide - even if blocked behind some form of registration, it should be possible to register/login/download the dataset via an english-based website.

**Comment by alpayariyak** [comment]
Hi @Phymond,

Thank you for your work. Would you be able to send this dataset over to aariyak@wpi.edu as well please?

**Comment by VietDunghacker** [comment]
Hi @Phymond,
Would you be able to send the dataset to me as well? My email is trungdunghoang92@gmail.com.

**Comment by joesharratt1229** [comment]
Hi @Phymond,

Could you please send the dataset to me too? My email is bi22854@bristol.ac.uk

Thanks

**Comment by tuannm2914** [comment]
Hi @Phymond,

Could you please send the dataset to me? My email is tuannm2914@gmail.com

Thank you so much

**Comment by DeepApps91** [comment]
@Phymond 
Could you please send the dataset to me? tintinkool@gmail.com
Thank you.

**Comment by TuanAnhNguyen14111998** [comment]
@Phymond
Could you please send the dataset to me?
My email is: nguyentuananh14111998@gmail.com
Thank you so much!

**Comment by cooleel** [comment]
Could you please send me the datatset? I was not able to get the registration work on that website.
cooleel@gmail.com 
@Phymond 
Thanks a lot!

**Comment by mshanKT** [comment]
Could you send me the dataset?
My email address is h19920918@gmail.com
@Phymond 

Thank you

**Comment by RubanSeven** [comment]
Could you send me the dataset?
My email address is [zhuhejun2019@gmail.com](mailto:zhuhejun2019@gmail.com)
@Phymond 

Thank you

**Comment by Aman9431257** [comment]
Could you send me the dataset?
My email address is aman9431257@gmail.com
@Phymond
